# Generated by Django 5.1.4 on 2024-12-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0004_alter_event_category_alter_event_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('Manager', 'Manager'), ('Staff', 'Staff')], max_length=10)),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
